/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminPortalSecureAccess8f92jRouteImport } from './routes/admin-portal-secure-access-8f92j'
import { Route as IndexRouteImport } from './routes/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortalSecureAccess8f92jRoute =
  AdminPortalSecureAccess8f92jRouteImport.update({
    id: '/admin-portal-secure-access-8f92j',
    path: '/admin-portal-secure-access-8f92j',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-portal-secure-access-8f92j': typeof AdminPortalSecureAccess8f92jRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-portal-secure-access-8f92j': typeof AdminPortalSecureAccess8f92jRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-portal-secure-access-8f92j': typeof AdminPortalSecureAccess8f92jRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-portal-secure-access-8f92j'
    | '/contact'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin-portal-secure-access-8f92j' | '/contact' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin-portal-secure-access-8f92j'
    | '/contact'
    | '/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminPortalSecureAccess8f92jRoute: typeof AdminPortalSecureAccess8f92jRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-portal-secure-access-8f92j': {
      id: '/admin-portal-secure-access-8f92j'
      path: '/admin-portal-secure-access-8f92j'
      fullPath: '/admin-portal-secure-access-8f92j'
      preLoaderRoute: typeof AdminPortalSecureAccess8f92jRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminPortalSecureAccess8f92jRoute: AdminPortalSecureAccess8f92jRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
